# Resilio Sync.
version: '3'
services:
  resilio-syncd:
    image: linuxserver/resilio-sync
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./data/config:/config
      - ./data/downloads:/downloads
      - ./data/sync:/sync
    environment:
      - PUID=1000
      - PGID=1000
    container_name: resilio-syncd
#    restart: unless-stopped
    restart: always
