# PHP7 codeigniter4.
# Run cmd: docker cp phpfpmd:/usr/local/etc ./php.d
version: '3'
services:
  httpd:
    image: nginx:1.19.7-alpine
    ports:
      - '84:80'
#      - '443:443'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./nginx.d/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx.d/mime.types:/etc/nginx/mime.types
      - ./nginx.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.d/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - ./codeigniter:/var/www/html:rw
    links:
      - fpmd
    restart: always

  fpmd:
    build: .
#    ports:
#      - '9000:9000'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./php.d:/usr/local/etc
      - ./codeigniter:/var/www/html:rw
    restart: always
