# Atlassian Confluence.
# https://hub.docker.com/r/cptactionhank/atlassian-confluence
version: '3'
services:
  atlan_confluence:
#    image: cptactionhank/atlassian-confluence:7.8.1
    build: .
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - ./confluence-data:/var/atlassian/application-data/confluence
      - ./mysql-connector-java-5.1.49.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-5.1.49.jar
      - ./atlassian-agent.jar:/opt/atlassian/jira/atlassian-agent.jar
#      - /etc/localtime:/etc/localtime
    restart: always
