# Atlassian Confluence.
# https://hub.docker.com/r/atlassian/confluence-server
version: '3'
services:
  atlan_confluence:
#    image: cptactionhank/atlassian-confluence:7.8.3
#    image: atlassian/confluence-server:7.8.1-alpine
    build: .
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - ./confluence-data:/var/atlassian/application-data/confluence
      - ./mysql-connector-java-5.1.49.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-5.1.49.jar
#      - ./atlassian-extras-decoder-v2-3.2.jar:/opt/atlassian/confluence/WEB-INF/lib/atlassian-extras-decoder-v2-3.2.jar     
      - ./atlassian-agent.jar:/opt/atlassian/jira/atlassian-agent.jar

#      - /etc/localtime:/etc/localtime
#    networks:
#      - traefik
#    environment:
#      JVM_SUPPORT_RECOMMENDED_ARGS: -Djavax.net.ssl.trustStore=/var/atlassian/application-data/confluence/cacerts 
    restart: always
