# MediaWiki.
version: '3.3'
services:
  mediawiki:
    image: mediawiki:1.32.5
    ports:
      - 8080:80
    volumes:
      - ./images:/var/www/html/images:rw
      - ./data:/var/www/data:rw
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
    restart: always
