# Atlassian Bitbucket.
# https://hub.docker.com/r/cptactionhank/atlassian-bitbucket
version: '3'
services:
  atlan_bitbucket:
#    image: atlassian/bitbucket-server:7.9.1
    build: .
    ports:
      - '7990:7990'
      - '7999:7999'
    volumes:
      - ./mysql-connector-java-5.1.49.jar:/var/atlassian/application-data/bitbucket/lib/mysql-connector-java-5.1.49.jar
      - ./atlassian-agent.jar:/var/atlassian/bitbucket/atlassian-agent.jar
#      - /etc/localtime:/etc/localtime
      - ./data:/var/atlassian/application-data/bitbucket
    container_name: bitbucketd
    restart: always
