FROM atlassian/bitbucket-server:7.9.1
#FROM atlassian/bitbucket-server:7.6.1
USER root
COPY "atlassian-agent.jar" /opt/atlassian/bitbucket/
COPY "_start-webapp.sh" /opt/atlassian/bitbucket/bin/_start-webapp.sh
