# PHP.
version: '3.3'
services:
  apache:
    image: php:7.3-apache
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/usr/local/etc/php/conf.d
      - ./html:/var/www/html:rw
#    environment:
#      MYSQL_DATABASE: exampledb
#      MYSQL_USER: exampleuser
#      MYSQL_PASSWORD: examplepass
#      MYSQL_RANDOM_ROOT_PASSWORD: rootexample
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
