# NextCloud.
version: '3'
services:
  nginx:
    image: nextcloud:20.0.6-apache
    ports:
      - '8880:80'
    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./db.data:/var/lib/mysql # MySQL / MariaDB Data
#      - ./db.data:/var/lib/postgresql/data #PostgreSQL Data
      - ./nextcloud:/var/www/html
    restart: always
