# NextCloud.
version: '3'
services:
  nginx:
    image: nextcloud:20.0.6-apache
#    image: nextcloud:20.0.6-fpm-alpine
    ports:
      - '8880:80'
    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./db:/var/lib/mysql # MySQL / MariaDB Data
#      - ./db:/var/lib/postgresql/data #PostgreSQL Data
      - ./nextcloud:/var/www/html
    restart: always
