# Gitlab.
version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:13.2.4-ce.0
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./conf:/etc/gitlab
      - ./etc:/var/opt/gitlab/gitlab-rails/etc
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab:rw
    restart: always
