# Nginx.
version: '3'
services:
  nginx:
    image: nginx:1.19.7-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./nginx.d/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx.d/mime.types:/etc/nginx/mime.types
      - ./nginx.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.d/conf.d:/etc/nginx/conf.d:ro
      - ./nginx.d/certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
#      - ./htmls:/usr/share/nginx/html:rw
      - ./htmls:/var/www/html:rw
#      - ./webdav:/usr/share/webdav:rw
    container_name: nginxd
    restart: always
