# Nginx.
version: '3.3'
services:
  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - '80:80'
    volumes:
#      - ./conf.d:/etc/nginx/
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html:rw
#      - ./html:/var/www/html:rw
    restart: always
