# Nginx.
version: '3'
services:
  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.d/conf.d:/etc/nginx/conf.d:ro
      - ./nginx.d/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx.d/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx.d/koi-utf:/etc/nginx/koi-utf
      - ./nginx.d/koi-win:/etc/nginx/koi-win
      - ./nginx.d/mime.types:/etc/nginx/mime.types
      - ./nginx.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.d/scgi_params:/etc/nginx/scgi_params
      - ./nginx.d/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx.d/win-utf:/etc/nginx/win-utf
      - ./logs:/var/log/nginx
#      - ./htmls:/usr/share/nginx/html:rw
      - ./htmls:/var/www/html:rw
#      - ./webdav:/usr/share/webdav:rw
    restart: always
