# wordpress.
version: '3'
services:
  nginx:
    image: nginx:1.19.1-alpine
    ports:
      - '80:80'
#      - '443:443'
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./logs/nginx:/var/log/nginx
#      - ./htmls:/var/www/html:rw
    links:
      - phpd
    restart: always

  phpd:
    image: wordpress:5.5.3-php7.4-fpm-alpine
#    image: wordpress:php7.4-fpm-alpine
#    image: wordpress:5.5.3-php7.3-fpm-alpine
#    image: wordpress:php7.3-fpm-alpine
#    build: .
#    ports:
#      - '9000:9000'
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./wp-content:/var/www/html/wp-content:rw
#      - ./htmls:/var/www/html:rw
#      - ./etc/php:/usr/local/etc
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wp123
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysqldb
    restart: always

  mysqldb:
    image: mariadb:10.4.14
#    ports:
#      - '3306:3306'
    volumes:
#      - ./etc/mariadb:/etc/mysql
      - ./db.data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wp123
      MYSQL_ROOT_PASSWORD: sqlroot123
    restart: always
    