# MariaDB.
version: '3.3'
services:
  mariadb:
    image: mariadb:10.3.20
    ports:
      - '3306:3306'
    volumes:
#      - ./etc/my.cnf:/etc/mysql/my.cnf
      - ./db.data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: xuuidb
      MYSQL_USER: xuui
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: rootpasswd@xuui
    restart: always
