# MariaDB.
version: '3.3'
services:
  mariadb:
    image: mariadb:10.4.12
#    image: mariadb:10.3.22
#    image: mariadb:10.2.31
    ports:
      - '3306:3306'
    volumes:
#      - ./my.cnf:/etc/mysql/my.cnf
      - ./db.data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: xuuidb
      MYSQL_USER: xuui
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: rootpasswd@xuui
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
