# MariaDB.
version: '3'
services:
  mariadb:
    image: linuxserver/mariadb:alpine-10.5.8-r0-ls3
#    image: mariadb:10.5.8
#    image: mariadb:10.4.17
#    image: mariadb:10.3.27
#    image: mariadb:10.2.36
#    image: mariadb:10.1.48
    ports:
      - '3306:3306'
    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./my.cnf:/etc/mysql/my.cnf
      - ./db.conf.d:/etc/mysql/conf.d
      - ./db.data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: xuuidb
      MYSQL_USER: xuui
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: rootpasswd@xuui
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
