# MySQL.
version: '3.3'
services:
  mysqldb:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: rootexample
    volumes:
      - ./db:/var/lib/mysql:rw

#  wordpress:
#    image: wordpress
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      WORDPRESS_DB_HOST: mysqldb
#      WORDPRESS_DB_USER: exampleuser
#      WORDPRESS_DB_PASSWORD: examplepass
#      WORDPRESS_DB_NAME: exampledb
#    volumes:
#      - ./wordpress:/var/www/html

