# MySQL.
version: '3'
services:
  mysqldb:
    image: mysql:8.0.22
#    image: mysql:5.7.32
#    image: mysql:5.6.50
    ports:
      - '3306:3306'
    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./my.cnf:/etc/mysql/my.cnf
      - ./db.conf.d:/etc/mysql/conf.d
      - ./db.data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: rootexample
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
