# Minecraft.
version: '3'
services:
  minecraftd:
    image: itzg/minecraft-server
    ports:
      - '25565:25565'
    volumes:
      - ./data:/data
    environment:
      VERSION: 1.7.10
      FORGEVERSION: 10.13.4.1448
      TYPE: FORGE
      EULA: TRUE
    restart: always
