# Minecraft.
version: '3'
services:
  minecraftd:
#    image: itzg/minecraft-server
#    image: kitematic/minecraft
    build: .
    ports:
      - '25565:25565'
    volumes:
      - ./data:/data
    environment:
      VERSION: 1.14.4
      FORGEVERSION: 28.1.56
#      TYPE: FORGE
#      EULA: TRUE
    deploy:
      resources:
        limits:
#          cpus: '0.50'
          memory: 1024M
        reservations:
#          cpus: '0.25'
          memory: 512M
    restart: always
