# Atlassian.
# Atlassian Bitbucket.
# https://hub.docker.com/r/atlassian/bitbucket-server
# docker pull atlassian/bitbucket-server:7.6.1

# Atlassian Confluence.
# https://hub.docker.com/r/atlassian/confluence-server
# docker pull atlassian/confluence-server:7.10.0
# docker pull cptactionhank/atlassian-confluence:7.9.3

# Atlassian Jira.
# https://hub.docker.com/r/atlassian/jira-software
# docker pull atlassian/jira-software:8.7.1
version: '3'
services:
  jirad:
    build: ./jira
    ports:
      - '8080:8080'
    volumes:
      - ./atlassian-agent.jar:/opt/atlassian/jira/atlassian-agent.jar
      - ./mysql-connector-java-5.1.49-bin.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/mysql-connector-java-5.1.49-bin.jar
#      - /etc/localtime:/etc/localtime
      - ./data/jira:/var/atlassian/application-data/jira:rw
#      - ./data/jira:/var/atlassian/jira:rw    #By.cptactionhank/atlassian-jira
    environment:
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 1024m
      JVM_RESERVED_CODE_CACHE_SIZE: 1024m
    links:
      - atlabd
    restart: always
    networks:
        aasianw:
          ipv4_address: 172.240.0.11

  confluenced:
    build: ./confluence
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - ./atlassian-agent.jar:/opt/atlassian/confluence/atlassian-agent.jar
      - ./atlassian-extras-decoder-v2-3.4.1.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-extras-decoder-v2-3.4.1.jar
      - ./mysql-connector-java-5.1.49.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-5.1.49.jar
#      - /etc/localtime:/etc/localtime
      - ./data/confluence:/var/atlassian/application-data/confluence:rw
#      - ./data/confluence:/var/atlassian/confluence:rw    #By.cptactionhank/atlassian-confluence
    environment:
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 1024m
      JVM_RESERVED_CODE_CACHE_SIZE: 1024m
    links:
      - atlabd
    restart: always
    networks:
        aasianw:
          ipv4_address: 172.240.0.12

#  bitbucketd:
##    image: atlassian/bitbucket-server:7.6.1
#    build: ./bitbucket
#    ports:
#      - '7990:7990'
#      - '7999:7999'
#    volumes:
#      - ./atlassian-agent.jar:/opt/atlassian/bitbucket/atlassian-agent.jar
##      - ./atlassian-extras-decoder-v2-3.4.1.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/atlassian-extras-decoder-v2-3.4.1.jar
#      - ./mysql-connector-java-5.1.49.jar:/var/atlassian/application-data/bitbucket/lib/mysql-connector-java-5.1.49.jar
##      - /etc/localtime:/etc/localtime
#      - ./data/bitbucket:/var/atlassian/application-data/bitbucket  
##    environment:
#    links:
#      - atlabd
#    restart: always
#    networks:
#        aasianw:
#          ipv4_address: 172.240.0.13

  atlabd:
#    image: mysql:8.0.23
    image: mariadb:10.5.9
    ports:
      - '3307:3306'
    volumes:
#      - ./my.cnf:/etc/mysql/my.cnf
      - ./db.conf.d:/etc/mysql/conf.d
      - ./db.data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd@Atlassian
    restart: always
    networks:
        aasianw:
          ipv4_address: 172.240.0.240

# Confluence 不支持数据库排序规则 “utf8mb4_general_ci"。 您需要使用 "。 
# 可选参数有：READ-UNCOMMITTED, READ-COMMITTED, REPEATABLE-READ, SERIALIZABLE.
# [mysqld]
# transaction-isolation = READ-COMMITTED

networks:
   aasianw:
      ipam:
         config:
         - subnet: 172.240.0.0/16
           gateway: 172.240.0.1
