# PHP7.
version: '3.3'
services:
  apache:
    image: php:7.4.5-fpm-alpine3.11
#    image: php:7.3.17-fpm-alpine3.11
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/usr/local/etc/php/conf.d
      - ./htmls:/var/www/html:rw
    restart: always
