# PHP7.
version: '3'
services:
  apache:
    image: php:7.4.10-fpm-alpine3.12
#    image: php:7.3.22-fpm-alpine3.12
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/usr/local/etc/php/conf.d
      - ./htmls:/var/www/html:rw
    restart: always
