# PHP7.
# Run cmd: docker cp phpfpmd:/usr/local/etc ./php.d
version: '3'
services:
  nginxd:
    image: nginx:1.19.1-alpine
    ports:
      - '81:80'
#      - '443:443'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./nginx.d/conf.d:/etc/nginx/conf.d:ro
      - ./nginx.d/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx.d/mime.types:/etc/nginx/mime.types
      - ./nginx.d/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./htmls:/var/www/html:rw
    links:
      - phpfpmd
    restart: always

  phpfpmd:
#    image: php:7.4.10-fpm-alpine3.12
#    image: php:7.3.22-fpm-alpine3.12
    build: .
#    ports:
#      - '9000:9000'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./php.d:/usr/local/etc
      - ./htmls:/var/www/html:rw
    restart: always
