# wiznote.
version: '3.3'
services:
  Wiz:
    image: wiznote/wizserver
    ports:
      - '80:80'
    volumes:
      - ./wizdata:/wiz/storage:rw
    restart: always
    environment:
      SEARCH: true
    command: -it
