# wiznote.
# http://www.wiz.cn/zh-cn/docker
version: '3'
services:
  Wiz:
    image: wiznote/wizserver
    ports:
      - '8088:80'
      - '9269:9269/udp'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./wizdata:/wiz/storage:rw
    restart: always
    environment:
      SEARCH: 'false' #'true'
