# wiznote.
# http://www.wiz.cn/zh-cn/docker
version: '3.3'
services:
  Wiz:
    image: wiznote/wizserver
#    image: wiznote/wizserver-armv7 #rpi
    ports:
      - '80:80'
      - '9269:9269/udp'
    volumes:
      - ./wizdata:/wiz/storage:rw
      - /etc/localtime:/etc/localtime
    restart: always
    environment:
#      SEARCH: 'true'
