# Gogs.
version: '3'
services:
  gogs:
#    image: gogs/gogs:latest
    image: gogs/gogs:0.12.3
#    image: gogs/gogs-rpi:0.12.3 # rpi
    ports:
      - "9080:3000"
      - "9022:22"
    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
      - ./data:/data:rw
      - ./backup:/backup:rw
    restart: always
