version: "3.7"
services:
  vlmcsd:
    build: .
    ports:
      - "1688:1688"
#    volumes: 
#      - ./vlmcsd:/root/vlmcsd:rw    #git clone --branch master --single-branch https://github.com/Wind4/vlmcsd.git
    container_name: vlmcsd
    restart: always